name: hrm_dump_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  form_field_validator: ^1.1.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.2
  http: ^0.13.5
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  geocoding: ^2.1.0
  geolocator: ^14.0.0
  uuid: ^4.5.1
  file_picker: ^10.1.9
  flutter_launcher_icons: ^0.14.3
  flutter_background_service: ^5.0.5
  collapsible_sidebar: ^2.0.7
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  path: ^1.8.3


  #premission
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/HRM_logo.jpg"
