name: managify_hr
description: "ManagifyHR - Complete HR Management Solution for modern businesses. Track attendance, manage employees, and streamline HR processes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  collapsible_sidebar: ^2.0.7
  
  # Form & Validation
  form_field_validator: ^1.1.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3+1
  path_provider: ^2.0.15
  path: ^1.8.3
  
  # Network & HTTP
  http: ^0.13.5
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^14.0.0
  location: ^6.0.1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.5.1
  url_launcher: ^6.3.0
  table_calendar: ^3.0.9
  
  # File & Media
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  
  # Background Services
  flutter_background_service: ^5.0.5
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/Webutsav__3.png
    - assets/HRM_logo.jpg

# App Icons Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/HRM_logo.jpg"
  # iOS specific settings
  ios_content_configuration:
    adaptive_icon_background: "#FFFFFF"
  # Android specific settings  
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/HRM_logo.jpg"